version: "3.7"

services:
  server:
    container_name: backend
    command: sh -c "npm install && npm run dev"
    image: node:12-slim
    working_dir: /backend
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
    ports:
      - "3333:3333"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    container_name: frontend
    image: node:12-slim
    command: sh -c "npm install && npm start"
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
      - CI=true
    depends_on:
      - server
    ports:
      - "3005:3000"
